name: Deploy Model to Hugging Face Hub

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install huggingface_hub

      - name: Install Git LFS
        run: git lfs install

      - name: Train and save model
        run: python model.py

      - name: Push model to Hugging Face Hub
        env:
          HF_USERNAME: ${{ secrets.HF_USERNAME }}
          HF_REPO_NAME: ${{ secrets.HF_REPO_NAME }}
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python -c "
          from huggingface_hub import HfApi
          import os
          import sys

          hf_username = os.environ.get('HF_USERNAME')
          hf_repo_name = os.environ.get('HF_REPO_NAME')
          hf_token = os.environ.get('HF_TOKEN')

          if not all([hf_username, hf_repo_name, hf_token]):
              print('Error: One or more required secrets (HF_USERNAME, HF_REPO_NAME, HF_TOKEN) are not set in GitHub repository settings.')
              sys.exit(1)

          repo_id = f\"{hf_username}/{hf_repo_name}\"
          print(f'Uploading model to {repo_id}...')
          
          api = HfApi()
          api.upload_folder(
              folder_path='models',
              repo_id=repo_id,
              repo_type='model',
              token=hf_token
          )
          print('Upload complete.')
          "

      - name: Send deployment notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "✅ Deployment Successful | ${{ github.repository }}"
          to: ${{ secrets.EMAIL_RECIPIENT }}
          from: GitHub Actions Notifier <notifier@github.com>
          body: |
            Hello,

            The model for the repository ${{ github.repository }} has been successfully trained and deployed to the Hugging Face Hub.

            You can view the model here:
            https://huggingface.co/${{ secrets.HF_USERNAME }}/${{ secrets.HF_REPO_NAME }}

            Commit: ${{ github.sha }}
